### ISSUE TITLE
Failed at NPM Run Build

### ISSUE THREAD

**Issue by edwinsi** [howdyai/botkit-cms#18]
I did step by step to run it locally as stated in https://github.com/howdyai/botkit-cms
but error show after I exec "NPM Run Build"

![image](https://user-images.githubusercontent.com/48465590/54174646-2e208600-44ba-11e9-8077-23509f1dd34b.png)

I'll be very appreciate it if you can help...

Thanks before

**Comment by Skezzowski** [comment]
Try with "npm run start", but before this you should delete the #-s before the variables PLATFORM,USERS,TOKENS,BOT_NAME from the .env file. I forget to do it so I got an error :D

**Comment by poovarasanvasudevan** [comment]
same here , this is the logs
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\SOFTWARE\\nodejs\\node.exe',
1 verbose cli   'D:\\SOFTWARE\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle botkit-cms@0.0.3~prebuild: botkit-cms@0.0.3
6 info lifecycle botkit-cms@0.0.3~build: botkit-cms@0.0.3
7 verbose lifecycle botkit-cms@0.0.3~build: unsafe-perm in lifecycle true
8 verbose lifecycle botkit-cms@0.0.3~build: PATH: D:\SOFTWARE\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\CHATBOT\BOTCMS\botkit-cms\node_modules\.bin;C:\Program Files\Java\jre1.8.0_131\bin;C:\Program Files\Java\jre1.8.0_131\bin;C:\RailsInstaller\Git\cmd;C:\RailsInstaller\Ruby2.3.3\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\BMC Software\ARSystem\dataimporttool;C:\Program Files\TortoiseSVN\bin;D:\PostgreSQL\pg10\bin;C:\Users\poovarasanv\.cargo\bin;C:\Program Files\Java\jdk1.8.0_131\bin;D:\Poovarasan\software\ideaIU-2017.2.5.win\plugins\maven\lib\maven3\bin;D:\apache-tomcat-7.0.39\bin;D:\GitPortable\App\Git\bin;D:\SOFTWARE\nodejs;D:\hadoop\hadoop-2.9.0.tar\hadoop-2.9.0\bin;C:\Users\poovarasanv\AppData\Local\Programs\Git LFS;D:\SOFTWARE\spring\bin;D:\Python\python-3.6.6.amd64;D:\Python\python-3.6.6.amd64\Scripts;D:\Poovarasan\ID\plugins\maven\lib\maven3\bin;D:\Mingw\bin;C:\Program Files\TortoiseSVN\bin\;D:\Server\go\bin;D:\GITP\bin;D:\Poovarasan\sdk\emulator;D:\Poovarasan\sdk\platform-tools;D:\SOFTWARE\curl\bin
9 verbose lifecycle botkit-cms@0.0.3~build: CWD: D:\CHATBOT\BOTCMS\botkit-cms
10 silly lifecycle botkit-cms@0.0.3~build: Args: [ '/d /s /c', './node_modules/gulp/bin/gulp.js' ]
11 silly lifecycle botkit-cms@0.0.3~build: Returned: code: 1  signal: null
12 info lifecycle botkit-cms@0.0.3~build: Failed to exec build script
13 verbose stack Error: botkit-cms@0.0.3 build: `./node_modules/gulp/bin/gulp.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\SOFTWARE\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (D:\SOFTWARE\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid botkit-cms@0.0.3
15 verbose cwd D:\CHATBOT\BOTCMS\botkit-cms
16 verbose Windows_NT 6.1.7601
17 verbose argv "D:\\SOFTWARE\\nodejs\\node.exe" "D:\\SOFTWARE\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v10.15.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error botkit-cms@0.0.3 build: `./node_modules/gulp/bin/gulp.js`
22 error Exit status 1
23 error Failed at the botkit-cms@0.0.3 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by david-templeton** [comment]
Verify that gulp is installed with the command `gulp --version`.  Then use `gulp` instead of `npm run start`.

You should see something like this:
> [14:27:52] Finished 'copy-partials' after 32 ms
> [14:27:52] Starting 'copy-more-partials'...
> [14:27:52] Copying HTML partials...
> [14:27:52] Finished 'copy-more-partials' after 7.08 ms
> [14:27:52] Starting 'sass'...
> [14:27:52] Compiling Sass...
> [14:27:53] Finished 'sass' after 171 ms
> [14:27:53] Finished 'default' after 370 ms

Continue on with `npm start`.
