### ISSUE TITLE
Issue using botkit cms locally within botkit

### ISSUE THREAD

**Issue by mdemin914** [howdyai/botkit-cms#24]
Hey, 

I am trying to get botkit-cms working locally within a botkit app. I think this would be ideal for a production deployment, not having to rely on another server to be up.  

I am using 
```
"botkit": "^4.0.2",
"botkit-cms": "0.0.4",
"botkit-plugin-cms": "^1.0.1",
```

When I follow the directions and include:
```
var cms = require('botkit-cms')();
cms.useLocalStudio(controller);

cms.loadScriptsFromFile(__dirname + '/scripts.json').catch(function(err) {
  console.error('Error loading scripts', err);
});
```

I get the following error: `TypeError: Cannot set property 'evaluateTrigger' of undefined`.

I fixed [here](https://github.com/mdemin914/botkit-cms/commit/53559649f63fcc5f3c717b1a0a255d964726bbcb) this by changing the `controller.studio` references to be `controller.plugins.cms`. This seems to fix the problem and things seem to more or less work. The bot responds to the triggers that are setup.

However, there is an exception when the input is something that doesn't cause any triggers to be returned. 

```
Error in trigger handler undefined
(node:53014) UnhandledPromiseRejectionWarning: Error:
  at Botkit.<anonymous> (blah/blah/node_modules/botkit/src/core.ts:1036:27)
```

Thanks for any help or direction on how to continue looking into this.

**Comment by zwenza** [comment]
I have the same error, any ideas?

**Comment by etiennellipse** [comment]
@mdemin914 I applied your suggested partial fix to `botkit_mutagen.js` with the latest version of Botkit (4.5.0) and I am still getting the (almost) same error.

```
    controller.plugins.cms.evaluateTrigger = function(text) {
                                           ^

TypeError: Cannot set property 'evaluateTrigger' of undefined
    at module.exports (/...myproject/node_modules/botkit-cms/src/botkit_mutagen.js:4:44)
```

Am I missing something?

**Comment by benbrown** [comment]
The Botkit-cms plugin has not been properly updated yet to run locally in Botkit 4+.  So this is an imperfect solution for now.

**Comment by etiennellipse** [comment]
@benbrown Do you think this is fixable? I might have someone from my team look into this next week.

**Comment by benbrown** [comment]
Yeah it is definitely fixable.

**Comment by etiennellipse** [comment]
This should be fixed by https://github.com/howdyai/botkit/pull/1851 !
