### ISSUE TITLE
error when "npm start"

### ISSUE THREAD

**Issue by CrazyOptimist** [howdyai/botkit-cms#33]
Hi
I got this error when I try get the cms up and running;

`root@3b74527adc70:/app# npm start

> botkit-cms@0.0.3 start /app
> node index.js

internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '/app/src/api.js'
Require stack:
- /app/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/index.js:2:11)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/index.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! botkit-cms@0.0.3 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the botkit-cms@0.0.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-02T16_33_07_062Z-debug.log
`

Before that, "npm run build" was successful like this;

`root@3b74527adc70:/app# npm run build

> botkit-cms@0.0.3 build /app
> ./node_modules/gulp/bin/gulp.js

[16:32:09] Using gulpfile /app/gulpfile.js
[16:32:09] Starting 'default'...
[16:32:09] Starting 'controller-concat'...
[16:32:09] Concatenating and Copying Controllers...
[16:32:10] Finished 'controller-concat' after 26 ms
[16:32:10] Starting 'copy-partials'...
[16:32:10] Copying HTML partials...
[16:32:10] Finished 'copy-partials' after 7.53 ms
[16:32:10] Starting 'copy-more-partials'...
[16:32:10] Copying HTML partials...
[16:32:10] Finished 'copy-more-partials' after 4.99 ms
[16:32:10] Starting 'sass'...
[16:32:10] Compiling Sass...
[16:32:10] Finished 'sass' after 5.73 ms
[16:32:10] Finished 'default' after 47 ms
`

Any idea?
Thank you in advance!

**Comment by CrazyOptimist** [comment]
Oh, I am sorry, was my fault.
This was the error in my Dockerfile:
`COPY ./botkit-cms/ /app/`
Solved after I removed asterisk from the command.
By the way, can I push the dockerized version?
